### ISSUE TITLE
支持作者大佬，坐等排列三

### ISSUE THREAD

**Issue by B0luo** [KittenCN/predict_Lottery_ticket_pytorch#1]
predict_Lottery_ticket这个项目排三写的很好，就是有些小bug。坐等作者大佬迁移重写，另外，有没有兴趣建个交流群好呐喊加油！

**Comment by KittenCN** [comment]
有哪些bug，可以提出来，我现在重点是搞股票预测的项目,迁移可能要滞后了。

**Comment by B0luo** [comment]
好的 ，我提在那个项目上
