### ISSUE TITLE
跑大乐透报错

### ISSUE THREAD

**Issue by Cold-Stars** [KittenCN/predict_Lottery_ticket_pytorch#9]
![image](https://github.com/KittenCN/predict_Lottery_ticket_pytorch/assets/113192545/2a057024-ec29-4fba-95ef-73f31aadccf9)

运行的命令：python run_train_model.py --windows_size 3,5,7 --red_epochs 1 --blue_epochs 1 --batch_size 64 --split_time 21351

**Comment by KittenCN** [comment]
你这个命令是跑快乐8的，目前这个项目也只适配的没有篮球的快乐8

**Comment by Cold-Stars** [comment]
> 你这个命令是跑快乐8的，目前这个项目也只适配的没有篮球的快乐8

上面那个报错我解决了，但是测试的时候报错了。

**Comment by Cold-Stars** [comment]
那我先跑下kl8的试试

**Comment by KittenCN** [comment]
默认是transform模型，我最近在修改特征计算，transform还没有匹配，可以用lstm，这个是匹配了的

**Comment by Cold-Stars** [comment]
> 默认是transform模型，我最近在修改特征计算，transform还没有匹配，可以用lstm，这个是匹配了的

用LSTM没跑通，然后我调试改改跑通了。我在尝试跑大乐透

**Comment by Cold-Stars** [comment]
跑通大乐透了
